base: # 基础配置，包含所有超参数
  train_path: dataset/yelp_academic_dataset_review.json # 训练集路径
  test_path: dataset/test.json # 测试集路径
  max_vocab_size: 50000 # 最大词汇表大小
  max_len: 256 # 最大句子长度
  min_freq: 5 # 词汇表词元最小频次
  batch_size: 64 # 批次大小
  epochs: 15 # 训练轮数
  learning_rate: 0.001 # 学习率
  device: cuda # 使用设备，'cuda' 或 'cpu'
  seed: 42 # 随机种子
  embed_dim: 256 # 词嵌入维度
  hidden_dim: 256 # LSTM隐藏层维度
  n_layers: 2 # LSTM层数
  dropout: 0.3 # Dropout概率
  use_layer_norm: true # 是否使用Layer Normalization
  use_residual: true # 是否使用残余连接
  lr_decay: true # 是否使用学习率衰减
  num_classes: 5 # 分类类别数

experiments: # 不同实验配置，只需写出修改的部分
  Baseline: {} # 基线配置
  dropout_0.5: 
    dropout: 0.5
  dropout_0:
    dropout: 0.0
  no_layer_norm:
    use_layer_norm: false
  no_lr_decay:
    lr_decay: false
  no_residual:
    use_residual: false
  layers_1:
    n_layers: 1
  layers_3:
    n_layers: 3

  
